# Generated by Django 2.2.2 on 2019-06-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_evaluator', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='language_evaluator.Language'),
            preserve_default=False,
        ),
    ]
