# Generated by Django 2.2.2 on 2019-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_evaluator', '0006_auto_20190621_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
