# Generated by Django 2.2.2 on 2019-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_evaluator', '0008_question_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
