# Generated by Django 2.2.4 on 2019-11-26 14:21

from django.db import migrations, models
import django.db.models.deletion
import language_evaluator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('language_evaluator', '0009_auto_20191123_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration', models.IntegerField(default=30)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Supported extensions: .mp3', upload_to='audio', validators=[language_evaluator.validators.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Supported extensions: .png, .jpg, .jpeg, .bmp, .gif', upload_to='images', validators=[language_evaluator.validators.validate_image_extension]),
        ),
        migrations.CreateModel(
            name='TestPresetQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_evaluator.Question')),
                ('test_preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_evaluator.TestPreset')),
            ],
        ),
    ]
