# Generated by Django 2.2.4 on 2019-11-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_evaluator', '0011_auto_20191126_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_evaluator.TestPreset'),
        ),
    ]
